spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.blog.model.domain
